#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# User routes
app.user.get:
  path: /api/users/{id}
  controller: App\Controller\User\GetUserAction
  methods: [ GET ]

app.user.create:
  path: /api/users
  controller: App\Controller\User\CreateUserAction
  methods: [ POST ]

app.user.update:
  path: /api/users/{id}
  controller: App\Controller\User\UpdateUserAction
  methods: [ PUT ]

# Profile routes
app.profile.get:
  path: /api/profiles/{id}
  controller: App\Controller\Profile\GetProfileByIdAction
  methods: [ GET ]

# Employee routes
app.employee.get:
  path: /api/employees
  controller: App\Controller\Employee\GetEmployeesAction
  methods: [ GET ]